artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1uaTm1Ba4o_RQO-C_6oiAfNRUVYkaNmIp/view?usp=sharing
  local_data_file: artifacts/data_ingestion/severstal-steel-defect-detection.zip
  unzip_dir: artifacts/data_ingestion
